# Generated by Django 5.0.6 on 2024-06-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_serial_no', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.FloatField(default=8.0)),
                ('shift', models.CharField(choices=[('Shift-1', 'Shift-1'), ('Shift-2', 'Shift-2'), ('Shift-3', 'Shift-3')], max_length=255)),
                ('produced_product', models.IntegerField()),
                ('bad_product', models.IntegerField()),
                ('unplanned_downtime', models.FloatField(default=0.0)),
                ('operating_time', models.FloatField()),
                ('ideal_cycle_time', models.FloatField()),
                ('date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
    ]
