# Generated by Django 5.0.6 on 2024-06-06 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='duration',
            field=models.FloatField(default=8.0, help_text='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='ideal_cycle_time',
            field=models.FloatField(help_text='Ideal cycle time in seconds'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='operating_time',
            field=models.FloatField(help_text='Available Operating time in hours'),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='unplanned_downtime',
            field=models.FloatField(default=0.0, help_text='Unplanned downtime in hours'),
        ),
        migrations.AlterUniqueTogether(
            name='productionlog',
            unique_together={('machine', 'shift', 'date')},
        ),
    ]
